DELIMITER $$

CREATE PROCEDURE `spCommitProductMasterFile`()
BEGIN
	IF TRUE THEN

		INSERT INTO `onix`.`productmasterfile` (

					`ONIXProductRef`,
					`PPN`,
					`ISBN10`,
					`RevISBN10`,
					`ISBN13`,
					`RevISBN13`,
					`EAN13`,
					`UPC`,
					`ISMN`,
					`DOI`,
					`LCCN`,
					`GTIN14`,
					`Title`,
					`SubTitle`,
					`SeriesTitle`,
					`TTitle`,
					`NPTTitle`,
					`NPSubTitle`,
					`NPSeriesTitle`,
					`Author`,
					`Illustrator`,
					`Translator`,
					`Imprint`,
					`Supplier`,
					`Copyright`,
					`Edition`,
					`CaseQty`,
					`Height`,
					`Width`,
					`Depth`,
					`DimensionsUM`,
					`Weight`,
					`WeightUM`,
					`Format`,
					`FormDetail`,
					`FormatDescription`,
					`Availability`,
					`Expected`,
					`Price`,
					`NetPrice`,
					`Denomination`,
					`Opened`,
					`Updated`,
					`Descriptions`,
					`StockedBy`,
					`deducedPrice`,
					`supplierOfOrigin`,
					`bisac`)
		SELECT		
					`ONIXProductRef`,
					`PPN`,
					`ISBN10`,
					`RevISBN10`,
					`ISBN13`,
					`RevISBN13`,
					`EAN13`,
					`UPC`,
					`ISMN`,
					`DOI`,
					`LCCN`,
					`GTIN14`,
					`Title`,
					`SubTitle`,
					`SeriesTitle`,
					`TTitle`,
					`NPTTitle`,
					`NPSubTitle`,
					`NPSeriesTitle`,
					`Author`,
					`Illustrator`,
					`Translator`,
					`Imprint`,
					`Supplier`,
					`Copyright`,
					`Edition`,
					`CaseQty`,
					`Height`,
					`Width`,
					`Depth`,
					`DimensionsUM`,
					`Weight`,
					`WeightUM`,
					`Format`,
					`FormDetail`,
					`FormatDescription`,
					`Availability`,
					`Expected`,
					`Price`,
					`NetPrice`,
					`Denomination`,
					`Opened`,
					`Updated`,
					`Descriptions`,
					`StockedBy`,
					`deducedPrice`,
					`supplierOfOrigin`,
					`bisac`
		FROM 		
					`onix`.`productmasterfile_stage`;

	ELSE

		UPDATE 		`onix`.`productmasterfile` pmf,
				(
					SELECT	
							`ONIXProductRef`,
							`PPN`,
							`ISBN10`,
							`RevISBN10`,
							`ISBN13`,
							`RevISBN13`,
							`EAN13`,
							`UPC`,
							`ISMN`,
							`DOI`,
							`LCCN`,
							`GTIN14`,
							`Title`,
							`SubTitle`,
							`SeriesTitle`,
							`TTitle`,
							`NPTTitle`,
							`NPSubTitle`,
							`NPSeriesTitle`,
							`Author`,
							`Illustrator`,
							`Translator`,
							`Imprint`,
							`Supplier`,
							`Copyright`,
							`Edition`,
							`CaseQty`,
							`Height`,
							`Width`,
							`Depth`,
							`DimensionsUM`,
							`Weight`,
							`WeightUM`,
							`Format`,
							`FormDetail`,
							`FormatDescription`,
							`Availability`,
							`Expected`,
							`Price`,
							`NetPrice`,
							`Denomination`,
							`Opened`,
							`Updated`,
							`Descriptions`,
							`StockedBy`,
							`deducedPrice`,
							`supplierOfOrigin`,
							`bisac`
					FROM	`onix`.`productmasterfile_stage` pmfs_derived
					WHERE	pmfs_derived.id = id
				) pmfs

		SET
					pmf.`ONIXProductRef` = pmfs.ONIXProductRef,
					pmf.`PPN` = pmfs.PPN,
					pmf.`ISBN10` = pmfs.ISBN10,
					pmf.`RevISBN10` = pmfs.RevISBN10,
					pmf.`ISBN13` = pmfs.ISBN13,
					pmf.`RevISBN13` = pmfs.RevISBN13,
					pmf.`EAN13` = pmfs.EAN13,
					pmf.`UPC` = pmfs.UPC,
					pmf.`ISMN` = pmfs.ISMN,
					pmf.`DOI` = pmfs.DOI,
					pmf.`LCCN` = pmfs.LCCN,
					pmf.`GTIN14` = pmfs.GTIN14,
					pmf.`Title` = pmfs.Title,
					pmf.`SubTitle` = pmfs.SubTitle,
					pmf.`SeriesTitle` = pmfs.SeriesTitle,
					pmf.`TTitle` = pmfs.TTitle,
					pmf.`NPTTitle` = pmfs.NPTTitle,
					pmf.`NPSubTitle` = pmfs.NPSubTitle,
					pmf.`NPSeriesTitle` = pmfs.NPSeriesTitle,
					pmf.`Author` = pmfs.Author,
					pmf.`Illustrator` = pmfs.Illustrator,
					pmf.`Translator` = pmfs.Translator,
					pmf.`Imprint` = pmfs.Imprint,
					pmf.`Supplier` = pmfs.Supplier,
					pmf.`Copyright` = pmfs.Copyright,
					pmf.`Edition` = pmfs.Edition,
					pmf.`CaseQty` = pmfs.CaseQty,
					pmf.`Height` = pmfs.Height,
					pmf.`Width` = pmfs.Width,
					pmf.`Depth` = pmfs.Depth,
					pmf.`DimensionsUM` = pmfs.DimensionsUM,
					pmf.`Weight` = pmfs.Weight,
					pmf.`WeightUM` = pmfs.WeightUM,
					pmf.`Format` = pmfs.Format,
					pmf.`FormDetail` = pmfs.FormDetail,
					pmf.`FormatDescription` = pmfs.FormatDescription,
					pmf.`Availability` = pmfs.Availability,
					pmf.`Expected` = pmfs.Expected,
					pmf.`Price` = pmfs.Price,
					pmf.`NetPrice` = pmfs.NetPrice,
					pmf.`Denomination` = pmfs.Denomination,
					pmf.`Opened` = pmfs.Opened,
					pmf.`Updated` = pmfs.Updated,
					pmf.`Descriptions` = pmfs.Descriptions,
					pmf.`StockedBy` = pmfs.StockedBy,
					pmf.`deducedPrice` = pmfs.deducedPrice,
					pmf.`supplierOfOrigin` = pmfs.supplierOfOrigin,
					pmf.`bisac` = pmfs.bisac
		WHERE 
					`id` = 1;


	END IF;
END